-- =====================================================
-- SCRIPT DE CREACIÓN COMPLETA DE BASE DE DATOS
-- Sistema de Gestión de Gimnasio - Versión PostgreSQL 17
-- =====================================================

-- Funciones para triggers de timestamp
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- TABLA: USERS (Usuarios del sistema)
-- =====================================================
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    email_verified INTEGER DEFAULT 0,
    role TEXT NOT NULL DEFAULT 'usuario' CHECK (role IN ('admin', 'entrenador', 'cliente', 'usuario')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_email_verified ON users(email_verified);
CREATE INDEX idx_users_updated_at ON users(updated_at);

CREATE TRIGGER update_users_timestamp
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- TABLA: EMAIL_VERIFICATIONS
-- =====================================================
DROP TABLE IF EXISTS email_verifications CASCADE;

CREATE TABLE email_verifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    token TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_email_verifications_user_id ON email_verifications(user_id);
CREATE INDEX idx_email_verifications_token ON email_verifications(token);
CREATE INDEX idx_email_verifications_expires_at ON email_verifications(expires_at);
CREATE INDEX idx_email_verifications_updated_at ON email_verifications(updated_at);

CREATE TRIGGER update_email_verifications_timestamp
    BEFORE UPDATE ON email_verifications
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- TABLA: RESET_TOKENS
-- =====================================================
DROP TABLE IF EXISTS reset_tokens CASCADE;

CREATE TABLE reset_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    token TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_reset_tokens_user_id ON reset_tokens(user_id);
CREATE INDEX idx_reset_tokens_token ON reset_tokens(token);
CREATE INDEX idx_reset_tokens_expires_at ON reset_tokens(expires_at);
CREATE INDEX idx_reset_tokens_updated_at ON reset_tokens(updated_at);

CREATE TRIGGER update_reset_tokens_timestamp
    BEFORE UPDATE ON reset_tokens
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- TABLA: PLANES
-- =====================================================
DROP TABLE IF EXISTS planes CASCADE;

CREATE TABLE planes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    precio_mensual DECIMAL(10,2) NOT NULL,
    caracteristicas JSONB NOT NULL,
    acceso_entrenador INTEGER DEFAULT 0,
    activo INTEGER DEFAULT 1,
    color_tema TEXT DEFAULT '#3b82f6',
    orden_display INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_planes_nombre ON planes(nombre);
CREATE INDEX idx_planes_activo ON planes(activo);
CREATE INDEX idx_planes_acceso_entrenador ON planes(acceso_entrenador);
CREATE INDEX idx_planes_orden_display ON planes(orden_display);
CREATE INDEX idx_planes_updated_at ON planes(updated_at);

CREATE TRIGGER update_planes_timestamp
    BEFORE UPDATE ON planes
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- TABLA: CLIENTES
-- =====================================================
DROP TABLE IF EXISTS clientes CASCADE;

CREATE TABLE clientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL UNIQUE,
    dni VARCHAR(20) UNIQUE NOT NULL,
    numero_telefono VARCHAR(20),
    plan_id INTEGER NOT NULL,
    fecha_nacimiento DATE,
    genero VARCHAR(10) CHECK (genero IN ('masculino', 'femenino', 'otro')),
    num_tarjeta VARCHAR(19),
    fecha_tarjeta VARCHAR(20),
    cvv VARCHAR(4),
    fecha_inscripcion DATE DEFAULT CURRENT_DATE,
    estado VARCHAR(20) DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo', 'suspendido')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_usuario) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (plan_id) REFERENCES planes(id)
);

CREATE INDEX idx_clientes_id_usuario ON clientes(id_usuario);
CREATE INDEX idx_clientes_dni ON clientes(dni);
CREATE INDEX idx_clientes_plan_id ON clientes(plan_id);
CREATE INDEX idx_clientes_estado ON clientes(estado);
CREATE INDEX idx_clientes_updated_at ON clientes(updated_at);

CREATE TRIGGER update_clientes_timestamp
    BEFORE UPDATE ON clientes
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- TABLA: GYM_CLASES
-- =====================================================
DROP TABLE IF EXISTS gym_clases CASCADE;

CREATE TABLE gym_clases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT,
    duracion_minutos INTEGER DEFAULT 45,
    nivel VARCHAR(20) DEFAULT 'todos' CHECK (nivel IN ('principiante', 'intermedio', 'avanzado', 'todos')),
    max_participantes INTEGER DEFAULT 20,
    activo INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    color VARCHAR(50) DEFAULT 'bg-gray-100 border-gray-300 text-gray-800'
);

CREATE INDEX idx_gym_clases_nombre ON gym_clases(nombre);
CREATE INDEX idx_gym_clases_nivel ON gym_clases(nivel);
CREATE INDEX idx_gym_clases_activo ON gym_clases(activo);
CREATE INDEX idx_gym_clases_duracion ON gym_clases(duracion_minutos);
CREATE INDEX idx_gym_clases_updated_at ON gym_clases(updated_at);

CREATE TRIGGER update_gym_clases_timestamp
    BEFORE UPDATE ON gym_clases
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- TABLA: CLASES_PROGRAMADAS
-- =====================================================
DROP TABLE IF EXISTS clases_programadas CASCADE;

CREATE TABLE clases_programadas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clase INTEGER NOT NULL,
    id_instructor INTEGER NOT NULL,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    capacidad_maxima INTEGER NOT NULL DEFAULT 20,
    estado VARCHAR(20) DEFAULT 'activa',
    ubicacion VARCHAR(100),
    duracion_minutos INTEGER DEFAULT 60,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_clase) REFERENCES gym_clases(id) ON DELETE CASCADE,
    FOREIGN KEY (id_instructor) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(id_clase, id_instructor, fecha, hora)
);

CREATE INDEX idx_clases_programadas_fecha ON clases_programadas(fecha);
CREATE INDEX idx_clases_programadas_instructor ON clases_programadas(id_instructor);
CREATE INDEX idx_clases_programadas_clase ON clases_programadas(id_clase);
CREATE INDEX idx_clases_programadas_estado ON clases_programadas(estado);
CREATE INDEX idx_clases_programadas_updated_at ON clases_programadas(updated_at);

CREATE TRIGGER update_clases_programadas_timestamp
    BEFORE UPDATE ON clases_programadas
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- TABLA: RESERVAS
-- =====================================================
DROP TABLE IF EXISTS reservas CASCADE;

CREATE TABLE reservas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL,
    id_clase_programada INTEGER NOT NULL,
    estado VARCHAR(20) DEFAULT 'activa',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    FOREIGN KEY (id_clase_programada) REFERENCES clases_programadas(id) ON DELETE CASCADE,
    UNIQUE(id_cliente, id_clase_programada)
);

CREATE INDEX idx_reservas_cliente ON reservas(id_cliente);
CREATE INDEX idx_reservas_clase ON reservas(id_clase_programada);
CREATE INDEX idx_reservas_estado ON reservas(estado);
CREATE INDEX idx_reservas_updated_at ON reservas(updated_at);

CREATE TRIGGER update_reservas_timestamp
    BEFORE UPDATE ON reservas
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- TABLA: ENTRENADOR_CLIENTE_ASIGNACIONES
-- =====================================================
DROP TABLE IF EXISTS entrenador_cliente_asignaciones CASCADE;

CREATE TABLE entrenador_cliente_asignaciones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entrenador INTEGER NOT NULL,
    id_cliente INTEGER NOT NULL,
    estado TEXT DEFAULT 'activa' CHECK (estado IN ('activa', 'inactiva', 'completada')),
    fecha_asignacion DATE DEFAULT CURRENT_DATE,
    notas TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_entrenador) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    UNIQUE(id_entrenador, id_cliente, estado)
);

CREATE INDEX idx_entrenador_cliente_entrenador ON entrenador_cliente_asignaciones(id_entrenador);
CREATE INDEX idx_entrenador_cliente_cliente ON entrenador_cliente_asignaciones(id_cliente);
CREATE INDEX idx_entrenador_cliente_estado ON entrenador_cliente_asignaciones(estado);
CREATE INDEX idx_entrenador_cliente_updated_at ON entrenador_cliente_asignaciones(updated_at);

CREATE TRIGGER update_entrenador_cliente_asignaciones_timestamp
    BEFORE UPDATE ON entrenador_cliente_asignaciones
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- TABLA: EJERCICIOS
-- =====================================================
DROP TABLE IF EXISTS ejercicios CASCADE;

CREATE TABLE ejercicios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    categoria VARCHAR(50) NOT NULL DEFAULT 'General',
    descripcion TEXT,
    estado VARCHAR(20) DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ejercicios_nombre ON ejercicios(nombre);
CREATE INDEX idx_ejercicios_categoria ON ejercicios(categoria);
CREATE INDEX idx_ejercicios_estado ON ejercicios(estado);
CREATE INDEX idx_ejercicios_updated_at ON ejercicios(updated_at);

CREATE TRIGGER update_ejercicios_timestamp
    BEFORE UPDATE ON ejercicios
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- TABLA: ENTRENAMIENTOS_ASIGNADOS
-- =====================================================
DROP TABLE IF EXISTS entrenamientos_asignados CASCADE;

CREATE TABLE entrenamientos_asignados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entrenador INTEGER NOT NULL,
    id_cliente INTEGER NOT NULL,
    id_ejercicio INTEGER NOT NULL,
    fecha_entrenamiento DATE NOT NULL,
    series INTEGER NOT NULL DEFAULT 1 CHECK (series > 0 AND series <= 10),
    estado VARCHAR(20) DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'completado', 'cancelado')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_entrenador) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    FOREIGN KEY (id_ejercicio) REFERENCES ejercicios(id) ON DELETE RESTRICT,
    UNIQUE(id_entrenador, id_cliente, id_ejercicio, fecha_entrenamiento)
);

CREATE INDEX idx_entrenamientos_entrenador ON entrenamientos_asignados(id_entrenador);
CREATE INDEX idx_entrenamientos_cliente ON entrenamientos_asignados(id_cliente);
CREATE INDEX idx_entrenamientos_ejercicio ON entrenamientos_asignados(id_ejercicio);
CREATE INDEX idx_entrenamientos_fecha ON entrenamientos_asignados(fecha_entrenamiento);
CREATE INDEX idx_entrenamientos_estado ON entrenamientos_asignados(estado);
CREATE INDEX idx_entrenamientos_updated_at ON entrenamientos_asignados(updated_at);

CREATE TRIGGER update_entrenamientos_asignados_timestamp
    BEFORE UPDATE ON entrenamientos_asignados
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- TABLA: ENTRENAMIENTOS_REALIZADOS
-- =====================================================
DROP TABLE IF EXISTS entrenamientos_realizados CASCADE;

CREATE TABLE entrenamientos_realizados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL,
    id_ejercicio INTEGER NOT NULL,
    id_entrenamiento_asignado INTEGER,
    fecha_realizacion DATE NOT NULL,
    hora_inicio TIME,
    hora_fin TIME,
    series_realizadas INTEGER NOT NULL CHECK (series_realizadas > 0),
    repeticiones INTEGER CHECK (repeticiones > 0),
    peso_kg DECIMAL(5,2) CHECK (peso_kg >= 0),
    tiempo_segundos INTEGER CHECK (tiempo_segundos > 0),
    distancia_metros DECIMAL(8,2) CHECK (distancia_metros > 0),
    notas TEXT,
    valoracion INTEGER CHECK (valoracion >= 1 AND valoracion <= 5),
    tipo_registro VARCHAR(20) DEFAULT 'libre' CHECK (tipo_registro IN ('libre', 'planificado')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON DELETE CASCADE,
    FOREIGN KEY (id_ejercicio) REFERENCES ejercicios(id) ON DELETE RESTRICT,
    FOREIGN KEY (id_entrenamiento_asignado) REFERENCES entrenamientos_asignados(id) ON DELETE SET NULL
);

CREATE INDEX idx_entrenamientos_realizados_cliente ON entrenamientos_realizados(id_cliente);
CREATE INDEX idx_entrenamientos_realizados_ejercicio ON entrenamientos_realizados(id_ejercicio);
CREATE INDEX idx_entrenamientos_realizados_fecha ON entrenamientos_realizados(fecha_realizacion);
CREATE INDEX idx_entrenamientos_realizados_asignado ON entrenamientos_realizados(id_entrenamiento_asignado);
CREATE INDEX idx_entrenamientos_realizados_tipo ON entrenamientos_realizados(tipo_registro);
CREATE INDEX idx_entrenamientos_realizados_updated_at ON entrenamientos_realizados(updated_at);

CREATE TRIGGER update_entrenamientos_realizados_timestamp
    BEFORE UPDATE ON entrenamientos_realizados
    FOR EACH ROW
    EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- TRIGGER PARA ACTUALIZAR ESTADO DE ENTRENAMIENTO ASIGNADO
-- =====================================================
CREATE OR REPLACE FUNCTION update_entrenamiento_asignado_completado()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.id_entrenamiento_asignado IS NOT NULL THEN
        UPDATE entrenamientos_asignados 
        SET estado = 'completado', 
            updated_at = CURRENT_TIMESTAMP 
        WHERE id = NEW.id_entrenamiento_asignado;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_entrenamiento_asignado_completado
    AFTER INSERT ON entrenamientos_realizados
    FOR EACH ROW
    EXECUTE FUNCTION update_entrenamiento_asignado_completado();